on: [push]
name: CI

jobs:
  testing:
    name: Testing
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - uses: denoland/setup-deno@v1
      with:
        deno-version: v1.x
    - run: deno test --parallel --allow-net
#    - uses: actions/upload-artifact@v3
#      with:
#        name: lcov
#        path: cov_profile.lcov
